name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: exleonardo/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_2f3adf3f-05cf-4b1d-b2ec-ed5be72faf10 }}
          GH_TOKEN: ${{ secrets.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 }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_EDITORS: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
